bucket_no_upscale = true
bucket_reso_steps = 64
caption_dropout_rate = 0.1
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 15
flip_aug = true
gradient_accumulation_steps = 1
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
ip_noise_gamma = 0.1
log_with = "tensorboard"
logging_dir = "/workspace/kohya_ss/outputs/FuzzyBear_v3/log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0.1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 225
max_train_steps = 3000
metadata_author = "Sergio Valdueza - TFM Deep Learning MIOTI"
metadata_description = "LoRA entrenado sobre un modelo Fine Tuned SDXL Base 1.0, usando 8 im√°genes 1024x1024 de personajes de Fuzzy Bear de Fortnite. Dataset creado manualmente. Entrenado en una 1x A100 GPU con 40Gb de RAM."
metadata_license = "CC BY-NC-SA 4.0"
metadata_tags = "fortnite, fuzzy bear, sdxl, lora, 1024x1024, A100, Kohya"
metadata_title = "FuzzyBear_v3"
min_bucket_reso = 256
mixed_precision = "fp16"
network_alpha = 16
network_args = []
network_dim = 32
network_module = "networks.lora"
no_half_vae = true
noise_offset = 0.05
noise_offset_random_strength = true
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "/workspace/kohya_ss/outputs/FuzzyBear_v3/model"
output_name = "FuzzyBear_v3"
pretrained_model_name_or_path = "/workspace/kohya_ss/models/humanoid_05"
prior_loss_weight = 1
resolution = "1024,1024"
sample_every_n_epochs = 1
sample_every_n_steps = 100
sample_prompts = "/workspace/kohya_ss/outputs/FuzzyBear_v3/model/sample/prompt.txt"
sample_sampler = "dpm_2"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
save_state = true
save_state_on_train_end = true
text_encoder_lr = [ 5e-5, 5e-5,]
train_batch_size = 2
train_data_dir = "/workspace/kohya_ss/outputs/FuzzyBear_v3/img"
training_comment = "2nd LoRA FuzzyBear sobre FT_Humanoids_5e_vF. 8images, 50repeats, 2batch, 15epochs, 3000steps"
unet_lr = 0.0001
wandb_run_name = "FuzzyBear_v3"
xformers = true
